spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 2
      pool-name: KrakenPool
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    connection-timeout: 6000
server:
  port: 7000
  servlet:
    context-path: /rickandmorty
logging:
  level:
    com.automatizacion: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

URL_BASE_API: https://rickandmortyapi.com